// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.DataAccess.Data;

#nullable disable

namespace WebApplication1.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930050150_productSeed")]
    partial class productSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Scifi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Billy Spark",
                            Description = "Praesent vitae sodales libero.",
                            ISBN = "SWD9999001",
                            ListPrice = 99.0,
                            Price = 90.0,
                            Price100 = 80.0,
                            Price50 = 85.0,
                            Title = "Fortune of Time"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nancy Weaver",
                            Description = "Curabitur aliquet quam id dui posuere blandit.",
                            ISBN = "SWD9999002",
                            ListPrice = 105.0,
                            Price = 95.0,
                            Price100 = 85.0,
                            Price50 = 90.0,
                            Title = "Mystery of the Old"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George R. R. Brown",
                            Description = "Sed porttitor lectus nibh.",
                            ISBN = "SWD9999003",
                            ListPrice = 120.0,
                            Price = 110.0,
                            Price100 = 100.0,
                            Price50 = 105.0,
                            Title = "The Final Frontier"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Diana Prince",
                            Description = "Vivamus magna justo, lacinia eget consectetur sed.",
                            ISBN = "SWD9999004",
                            ListPrice = 115.0,
                            Price = 105.0,
                            Price100 = 95.0,
                            Price50 = 100.0,
                            Title = "Secrets of the Universe"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mark Twain",
                            Description = "Nulla porttitor accumsan tincidunt.",
                            ISBN = "SWD9999005",
                            ListPrice = 98.0,
                            Price = 88.0,
                            Price100 = 78.0,
                            Price50 = 83.0,
                            Title = "Adventures of Tomorrow"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Jane Austen",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            ISBN = "SWD9999006",
                            ListPrice = 125.0,
                            Price = 115.0,
                            Price100 = 105.0,
                            Price50 = 110.0,
                            Title = "Legends of the Past"
                        },
                        new
                        {
                            Id = 7,
                            Author = "H.P. Lovecraft",
                            Description = "Vestibulum ac diam sit amet quam vehicula elementum.",
                            ISBN = "SWD9999007",
                            ListPrice = 135.0,
                            Price = 125.0,
                            Price100 = 115.0,
                            Price50 = 120.0,
                            Title = "Voyage to the Stars"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Isaac Asimov",
                            Description = "Donec sollicitudin molestie malesuada.",
                            ISBN = "SWD9999008",
                            ListPrice = 145.0,
                            Price = 135.0,
                            Price100 = 125.0,
                            Price50 = 130.0,
                            Title = "Chronicles of the Unknown"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Stephen King",
                            Description = "Vivamus suscipit tortor eget felis porttitor volutpat.",
                            ISBN = "SWD9999009",
                            ListPrice = 110.0,
                            Price = 100.0,
                            Price100 = 90.0,
                            Price50 = 95.0,
                            Title = "Echoes of Eternity"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.K. Rowling",
                            Description = "Pellentesque in ipsum id orci porta dapibus.",
                            ISBN = "SWD9999010",
                            ListPrice = 130.0,
                            Price = 120.0,
                            Price100 = 110.0,
                            Price50 = 115.0,
                            Title = "Winds of Fate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
